project:
  type: website
  output-dir: docs

website:
  title: "Leaflet in R"
  navbar:
    left:
      - href: tutorial.qmd
        text: Tutorial
    right: 
      - icon: github
        href: https://github.com/matthh10/leaflet-demo
        aria-label: GitHub

format:
  html:
    theme: cosmo
    toc: true

editor: visual