project:
  type: website
  output-dir: docs

website:
  title: "Leaflet in R"
  navbar:
    left:
      - href: tutorial.qmd
        text: Tutorial
      - href: slides.qmd
        text: Slides
    right: 
      - icon: github
        href: https://github.com/matthh10/leaflet-demo
        aria-label: GitHub

format:
  html:
    theme:
      light: cosmo
      dark: solar
    toc: true

editor: visual